name: FieldRadio
version: '1.1-ALPHA'
main: arnett.fieldRadio.FieldRadio
api-version: '1.21'

commands:
  fieldradio:
    description: Main command
    aliases: [fieldradio, radio]
    permission: fieldradio.use
    usage: "Incorrect Usage (/radio <subcommand> ...)"

softdepend: [voicechat]
